# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 20:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=128)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('document', models.CharField(max_length=128)),
                ('due_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'Submissions',
                'verbose_name': 'Submission',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('academic_year', models.IntegerField()),
                ('semester', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'FAL Classes',
                'verbose_name': 'FAL Class',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Interview_Question_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Interview')),
            ],
            options={
                'verbose_name_plural': 'Interview Questions',
                'verbose_name': 'Interview Question',
            },
        ),
        migrations.CreateModel(
            name='Interview_Question_Video_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Interview Video Questions',
                'verbose_name': 'Interview Question Video',
            },
        ),
        migrations.CreateModel(
            name='LMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'LMS',
                'verbose_name': 'LMS',
            },
        ),
        migrations.CreateModel(
            name='LMS_Web_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_service_name', models.CharField(max_length=128)),
                ('web_service_method', models.CharField(max_length=128)),
                ('web_service_url', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'LMS Web Services',
                'verbose_name': 'LMS Web Service',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_Video_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Question')),
            ],
            options={
                'verbose_name_plural': 'Video Questions',
                'verbose_name': 'Video Question',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.LMS')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Interview_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Interview')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Assignment_Submission')),
            ],
            options={
                'verbose_name_plural': 'Interview Submissions',
                'verbose_name': 'Interview Submission',
            },
        ),
        migrations.CreateModel(
            name='User_Add_Ons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.LMS')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Add-ons',
                'verbose_name': 'User Add-ons',
            },
        ),
        migrations.CreateModel(
            name='User_Group_Role_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.User_Add_Ons')),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('tags', models.CharField(blank=True, max_length=128, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.User_Add_Ons')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('creation_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.User_Add_Ons')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Video')),
            ],
            options={
                'verbose_name_plural': 'Video Comments',
                'verbose_name': 'Video Comment',
            },
        ),
        migrations.CreateModel(
            name='Volunteer_User_Add_Ons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('canGetText', models.BooleanField(default=True)),
                ('workTitle', models.CharField(max_length=25)),
                ('isBusinessOwner', models.BooleanField(default=True)),
                ('workIndustry', models.CharField(max_length=25)),
                ('yearsInIndustry', models.IntegerField()),
                ('linkedinProfile', models.CharField(blank=True, max_length=128, null=True)),
                ('yearsSinceHSGraduation', models.IntegerField(choices=[(1, '1-4'), (2, '5-10'), (3, '11 or more'), (4, 'Have not graduated')])),
                ('collegeLevel', models.IntegerField(choices=[(1, '1-4'), (2, '5-10'), (3, '11 or more'), (4, 'Have not graduated')])),
                ('collegeMajor', models.CharField(blank=True, max_length=128, null=True)),
                ('interests', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foraliving.Interest')),
                ('skills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foraliving.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Volunteer add-ons',
                'verbose_name': 'Volunteer add-ons',
            },
        ),
        migrations.AddField(
            model_name='question_video_map',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Video'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.User_Add_Ons'),
        ),
        migrations.AddField(
            model_name='interview_question_video_map',
            name='interview_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Question_Video_Map'),
        ),
        migrations.AddField(
            model_name='interview_question_video_map',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Video'),
        ),
        migrations.AddField(
            model_name='interview_question_map',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Question'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewee', to='foraliving.User_Add_Ons'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='foraliving.User_Add_Ons'),
        ),
        migrations.AddField(
            model_name='class',
            name='lms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.LMS'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.School'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.User_Add_Ons'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='falClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Class'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.User_Add_Ons'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Question'),
        ),
    ]
