# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview_question_video_map',
            name='interview_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Interview_Question_Map'),
        ),
    ]
