# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0002_auto_20161121_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='foraliving.Assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='pending', max_length=128),
            preserve_default=False,
        ),
    ]
