# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0003_auto_20161122_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='assignment',
            new_name='assignments',
        ),
    ]
