# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0006_interview_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='date',
        ),
    ]
