# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0007_auto_20161122_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
