# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0009_auto_20161122_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
    ]
