# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0012_interview_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(max_length=128),
            preserve_default=False
        ),
    ]
