# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 22:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0013_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewee', to=settings.AUTH_USER_MODEL),
        ),
    ]
