# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0014_auto_20161130_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_user_add_ons',
            name='collegeLevel',
            field=models.IntegerField(choices=[(1, 'associate'), (2, "bachelor's"), (3, "master's"), (4, 'doctoral'), (5, 'none')]),
        ),
    ]
