# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0015_auto_20161201_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_user_add_ons',
            name='interests',
        ),
        migrations.AddField(
            model_name='volunteer_user_add_ons',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='foraliving.Interest'),
        ),
        migrations.RemoveField(
            model_name='volunteer_user_add_ons',
            name='skills',
        ),
        migrations.AddField(
            model_name='volunteer_user_add_ons',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='foraliving.Skill'),
        ),
    ]
