# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0017_auto_20161202_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_user_add_ons',
            name='interests',
        ),
        migrations.AddField(
            model_name='volunteer_user_add_ons',
            name='interests',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
