# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0019_auto_20161205_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foraliving.SimpleCategory', verbose_name='parent')),
            ],
            options={
                'verbose_name_plural': 'simple categories',
            },
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
