# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0020_simplecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_user_add_ons',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='foraliving.SimpleCategory'),
        ),
    ]
