# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0021_auto_20161207_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplecategory',
            name='parent',
        ),
        migrations.AlterModelManagers(
            name='skill',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foraliving.Skill', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='skill',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default=1, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='volunteer_user_add_ons',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='foraliving.Skill'),
        ),
        migrations.DeleteModel(
            name='SimpleCategory',
        ),
    ]
