# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0022_auto_20161207_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(default='contact', max_length=128),
        ),
    ]
