# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0023_skill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
        migrations.RemoveField(
            model_name='volunteer_user_add_ons',
            name='interests',
        ),
        migrations.AddField(
            model_name='volunteer_user_add_ons',
            name='interests',
            field=models.ManyToManyField(blank=True, max_length=128, null=True, to='foraliving.Interest'),
        ),
    ]
