# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0025_auto_20161208_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer_user_add_ons',
            options={},
        ),
        migrations.AlterField(
            model_name='volunteer_user_add_ons',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
