# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0026_auto_20161213_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Add_Ons', to='foraliving.User_Add_Ons')),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer_user_add_ons',
            name='collegeLevel',
            field=models.IntegerField(choices=[(1, 'Associate'), (2, "Bachelor's"), (3, "Master's"), (4, 'Doctoral'), (5, 'None')]),
        ),
    ]
