# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0027_auto_20170105_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='Student_Class',
        ),
    ]
