# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0028_auto_20170105_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_class',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Add_Ons', to=settings.AUTH_USER_MODEL),
        ),
    ]
