# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0031_auto_20170106_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(default='Interview Assignment description', max_length=256),
            preserve_default=False,
        ),
    ]
