# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0032_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.CharField(max_length=256),
        ),
    ]
