# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('foraliving', '0035_auto_20170113_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('falClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Class')),
            ],
            options={
                'verbose_name_plural': 'GroupClass',
                'ordering': ['name'],
            },
            bases=('auth.group',),
        ),
    ]
