# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('foraliving', '0036_groupclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupclass',
            name='falClass',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='GroupClass',
        ),
    ]
