# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('foraliving', '0037_auto_20170123_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foraliving.Class')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Class Groups',
                'verbose_name_plural': 'Class Groups',
            },
        ),
    ]
