# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraliving', '0038_class_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
